project:
  type: website

website:
  title: "Responsible AI examples and best practices for Marine Ecosystem Modeling"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: context-document-best-practices.qmd
        text: Context Document Best Practices
      - href: about.qmd
        text: About
      - href: glossary.qmd
        text: Glossary

format:
  html:
    theme: cosmo
    toc: true
    css: styles.css
